// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8supFbGTKkKhuwJYa4LCdj5q7w7zfZ7o',
    appId: '1:871336841990:web:18c8235843373568394487',
    messagingSenderId: '871336841990',
    projectId: 'appgarage-58527',
    authDomain: 'appgarage-58527.firebaseapp.com',
    storageBucket: 'appgarage-58527.firebasestorage.app',
    measurementId: 'G-5QVS0T9RL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEl1P3nLR9PXiS-spDn52lZ00uXAbxUEw',
    appId: '1:871336841990:android:6a7d81aff0405c8c394487',
    messagingSenderId: '871336841990',
    projectId: 'appgarage-58527',
    storageBucket: 'appgarage-58527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB6tVsXMk340MXFuUMluTa93VvBqcajck',
    appId: '1:871336841990:ios:b1f59f9b2c07b4e4394487',
    messagingSenderId: '871336841990',
    projectId: 'appgarage-58527',
    storageBucket: 'appgarage-58527.firebasestorage.app',
    iosBundleId: 'com.example.test1AppgardienbutFabrice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB6tVsXMk340MXFuUMluTa93VvBqcajck',
    appId: '1:871336841990:ios:b1f59f9b2c07b4e4394487',
    messagingSenderId: '871336841990',
    projectId: 'appgarage-58527',
    storageBucket: 'appgarage-58527.firebasestorage.app',
    iosBundleId: 'com.example.test1AppgardienbutFabrice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8supFbGTKkKhuwJYa4LCdj5q7w7zfZ7o',
    appId: '1:871336841990:web:794b2b80ecf096df394487',
    messagingSenderId: '871336841990',
    projectId: 'appgarage-58527',
    authDomain: 'appgarage-58527.firebaseapp.com',
    storageBucket: 'appgarage-58527.firebasestorage.app',
    measurementId: 'G-BS87XR9GVV',
  );

}